name: Go

on:
  push:
    branches: [ master ]

jobs:
  test-github-actions
  build:
    runs-on: ubuntu-latest
    steps:
      -run echo 'this is github actions'
      -run ls -alsh
      -run pwd
      -run whoami
